import * as React from 'react';
import Head from 'next/head';
import styled from 'styled-components';
import Button from '@material-ui/core/Button';
import {Container, CssBaseline, Grid, Typography} from '@material-ui/core';
import type {NextPage} from 'next';

const Home: NextPage = () => {
  const [count, setCount] = React.useState(0);
  const addCount = () => setCount(previousState => previousState + 1);
  const decreaseCount = () => setCount(previousState => previousState - 1);

  return (
    <S.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container component="main" maxWidth="sm">
        <CssBaseline />
        <S.Typography variant="h1">Hello World</S.Typography>
        <S.Typography variant="body1">{count}</S.Typography>
        <Grid container spacing={1}>
          <Grid item xs={12} sm={6}>
            <Button variant="contained" onClick={addCount} fullWidth>
              Test Button
            </Button>
          </Grid>
          <Grid item xs={12} sm={6}>
            <Button
              variant="contained"
              color="secondary"
              onClick={decreaseCount}
              fullWidth
            >
              Test Button
            </Button>
          </Grid>
        </Grid>
      </Container>
    </S.Container>
  );
};

export default Home;

const S = {
  Container: styled.div`
    min-height: 100vh;
  `,
  Typography: styled(Typography)`
    text-align: center;
  `,
};
